### ISSUE TITLE
Kunden-Fotos

### ISSUE THREAD

**Issue by JPruess** [th-koeln/wba1-2016-backslash#102]
Hallo Volker,
auf unserer OnePage gibt es einen kleinen Kapitelpunkt namens 'Über uns'. Dort stellt sich die Firma hinter Fubuizz nur ganz kurz und knapp vor.
Jetzt gab es die Überlegung, weil ihr ja eigentlich in GDVK im Prinzip die Kunden wart, ob dort Bilder von euch reingesetzt werden sollten/könnten. Was haltet ihr von der Idee?
Aktuell sind noch Platzhalterbilder drin die ganz einfach ersetzt werden könnten.
Sonst würden wir sie entweder drinnen lassen (obwohl diese doch recht 'formell' aussehen) oder uns irgendwo neue suchen, wenn ihr keine Fotos von euch drin haben möchtet.

Insgesamt handelt es sich um 3 Bilder und darunter die Position in der Firma.

Viele Grüße
Jared

**Comment by vschaefer** [comment]
Joa, finde ich gut die Idee.

**Comment by JPruess** [comment]
Super. :-)
Von dir und von Herrn Noss haben wir hier die Profilbilder dafür. Wir bräuchten nur noch ein Bild von Jorge,  please.

**Comment by jhfpereira** [comment]
https://www.dropbox.com/s/6a49n83eofvglfp/jorge.h.f.pereira.png?dl=0

**Comment by JPruess** [comment]
Vielen Dank! : )

**Comment by jhfpereira** [comment]
Denke mal, dass das Issue hier dann auch geclosed werden kann :)
