### ISSUE TITLE
T10 Fehlende Bilder Vereinsanpassung

### ISSUE THREAD

**Issue by JPruess** [th-koeln/wba1-2016-backslash#103]
Hallo liebes Asset-Team,
am Donnerstag ist die Helena aus Team 15 zu euch gekommen, weil wir dringend die beiden Bilder von der Vereinsanpassung brauchen. Vielleicht wurde es falsch verstanden:
Wir brauchen nicht die Hintergrundbilder sondern euer Layout/Screens von der Vereinsanpassung.
In der PDF mit allen Screens sind zwei stück drin.
Wir brauchen leider auch beide Screens.

Es wäre klasse, wenn ihr die an diesem Wochenende hochladen könnten, da wir sie leider dringend brauchen. 👍 Das wäre suuuuuuper. :)

Vielen Dank.
Gruß
T15

**Comment by jhfpereira** [comment]
Wäre gut gewesen, wenn ihr das Issue einem Mitglied von T10 assigned hättet, wie z. B. @DavidZibler.

Sollte T10 das Issue aber gesehen und geliefert haben, kann das Issue geclosed werden. Danke :)

**Comment by JPruess** [comment]
Wurde persönlich am Donnerstag erledigt.
