### ISSUE TITLE
Quizübersicht neuer Stand vom 11.11

### ISSUE THREAD

**Issue by Meredia** [th-koeln/wba1-2016-backslash#104]
Unser Code ist zu gut wie fertig, aber der Callapse funktioniert nicht so richtig.
Wir brauchen dringend dazu Hilfe.
Ihr findet den Code unter Neuer_Stand, dann zu T06_Quizübersicht Smartphone.

Gruß
Das T06- Team

**Comment by vschaefer** [comment]
In welchen von den Dateien steht denn der richtige Code?

**Comment by vschaefer** [comment]
Nach der Commit-History ist es T06_Quizübersicht Smartphone.html. Ist das korrekt?

**Comment by Meredia** [comment]
Ja, das muss das Richtige sein.

Am 12.11.2016 00:51 schrieb "Volker Schaefer" <notifications@github.com>:
