### ISSUE TITLE
T13 Bilder und Texte für die Quizübersicht.

### ISSUE THREAD

**Issue by vschaefer** [th-koeln/wba1-2016-backslash#106]
Wenn nicht schon vorhanden, benötigen wir für die Quizübersicht Bilder und Texte zu mindestens 10 Quizspielen.

**Comment by vschaefer** [comment]
Mir würde es auch erstmal reichen, wenn wir Bilder und Texte zu den bisher verfügbaren Quizspielen haben.

**Comment by micha997** [comment]
Hab jetzt noch ein paar bei der Übersicht hinzugefügt. Es sind jetzt insgesamt 11, aber nur die ersten 5 sind vollständig (mit Fragen und Highscore).

**Comment by vschaefer** [comment]
Existieren für die Übersicht auch Bilder?

**Comment by micha997** [comment]
Ja die URL zu den Bildern wird mit übergeben

**Comment by vschaefer** [comment]
Top, Danke :)

**Comment by nikcani** [comment]
Kann das hier geschlossen werden?
