### ISSUE TITLE
Zielsetzung T05-StatSchlusscreen

### ISSUE THREAD

**Issue by aaronseg** [th-koeln/wba1-2016-backslash#11]
- Wireframes ( Icons Bilder etc...) zusammensuchen
- HTML einteilung 
- Einteilung der Aufgaben innerhalb der Gruppe
- Am Donnerstag anfangen mit dem Grundgerüst

**Comment by jhfpereira** [comment]
Das Issue bitte schließen, sofern es fertig abgearbeitet wurde ("Close and comment").

Ggf. können die entstandenen Artefakte (wenn überhaupt) hier auch sicherheitshalber nochmal verlinkt werden.
