### ISSUE TITLE
T08 Präsentation und Dokumentation fertigstellen

### ISSUE THREAD

**Issue by jomehr** [th-koeln/wba1-2016-backslash#112]
- [x] unsere Teilpräsentation (Templates, Ajax, Verwendung der API/Jsons) für die Abschlusspräsentation erstellen

- [x] Dokumentation fertigstellen und ausbessern

**Comment by jomehr** [comment]
@l1fecoach Könnte das Dokuteam mal über unsere bisherige Doku drüberschauen, ob der bisherige Stand für euch in Ordnung ist und Feedback geben? Die schriftliche Funktionsweise des Templating ist hoffentlich bis Dienstag fertig.

**Comment by TNehmke** [comment]
Schriftliche Funktionsweise vom Templating ist fertig.
