### ISSUE TITLE
T04 Quizübersicht optimieren

### ISSUE THREAD

**Issue by vschaefer** [th-koeln/wba1-2016-backslash#119]
![schnappschuss 2016-11-19 19 13 27](https://cloud.githubusercontent.com/assets/2872395/20457465/4c963970-ae8c-11e6-8c18-e7f646d56013.png)
In der Quizübersicht besteht noch Optmierungsbedarf, insbesondere in der mobilen Ansicht.
Es wäre gut, wenn die Frage, alle Antworten und ggf. noch die Punkte unterhalb der Antworten, auf den Screen passen, ohne dass man scrollen muss.
Dazu schlage ich vor
- [x] das Hauptmenü während der Quizrunde auszublenden
- [x] den Timer in der mobilen Ansicht zu verkleinern
- [x] den Weißraum oberhalb und unterhalb des Timers zu verkleinern
- [x] die Höhe der Antwortbuttons zu verringern
- [x] wenn es immer noch nicht passt, den Weißraum unter der Frage verringern

Der Text auf den Antwortbuttons sitzt auch noch nicht so gut.
- [x] bitte hier die Position optimieren
- [x] Schrift in der mobilen Ansicht etwas vergrößern und den Durchschuss verringern

**Comment by dbljn** [comment]
Wie hast du das denn mit der Schrift in den Antwort-Buttons so "hingekriegt"? Also bei mir ist die immer zentriert, egal ob auf dem Rechner, Smartphone, Tablet oder sonst was.

**Comment by vschaefer** [comment]
Vielleicht liegt es am Browser. Ich habe im Firefox und Safari geguckt.

**Comment by Exokay88** [comment]
@vschaefer @dbljn 

> das quiz funktioniert nicht auf firefox. bitte benutzt chrome.

**Comment by vschaefer** [comment]
Gilt das auch für die vertikale Ausrichtung der Schrift?

**Comment by dbljn** [comment]
Ich kann ja leider nicht mehr ohne weiteres meinen Code ändern. Niklas, du könntest im Code noch ein paar Sachen abändern oder? Könntest du dann bitte die kleinste Mediaqueri auf 436px ändern? Leider rutscht momentan noch ein Feedback-Icon runter und mit den 436px wird das behoben.

**Comment by vschaefer** [comment]
Du könntest schon noch etwas ändern, das müsste dann nur in die App nachgepflegt werden :)
Oder @nikcani oder @Exokay88 zeigen dir die Stellen, wo du es selbst ändern kannst.

**Comment by nikcani** [comment]
@dbljn klar kann ich noch ein paar Sachen abändern, bei mir rutscht da aber kein Icon runter (du meinst doch die 10 Kreise unten, oder?) @vschaefer ich schaue mir auch mal an wie schnell und einfach man deine Vorschläge da umsetzen kann oder soll ich da auf @dbljn warten?

**Comment by vschaefer** [comment]
Überlasse ich euch :) Ihr könnt es euch ja auch aufteilen.

**Comment by dbljn** [comment]
Also ich habe nochmal bisschen mit der Boxhöhe rumgespielt, das Problem hierbei ist aber, dass es bei einigen Fragen sehr lange Antworten gibt und wenn ich die Boxhöhe dann reduzieren würde, passen die Antworten nicht mehr in die Box. Bei meiner Beispielfrage ist eine Antwort dabei, die in der kleinsten Ansicht drei volle Zeilen einnimmt und das ist das Maximum so einer Box...kleiner kann ich die Schrift auch nicht machen.

**Comment by nikcani** [comment]
So, ich habe jetzt eine sehr schöne Lösung für die Buttons gefunden, allerdings auf der Basis von Flexboxen mit leichten Problemen im Firefox, ich denke aber wir sollten das so in Kauf nehmen, da die Buttons sich so optimal dem Inhalt anpassen.

**Comment by nikcani** [comment]
habe jetzt alle Vorschläge umgesetzt, daher schließe ich das hier mal. @dbljn du kannst dir die Änderungen im gh-pages Branch anschauen und auch bei euch im Team einbauen.
