### ISSUE TITLE
Vorlagescreens mit Tags versehen

### ISSUE THREAD

**Issue by jomehr** [th-koeln/wba1-2016-backslash#12]
Wir werden die Vorlagen mit HTML-Tags versehen, damit die Teams der statischen Screens schonmal ein erstes Grundgerüst haben.

**Comment by jhfpereira** [comment]
Das Issue bitte schließen, sofern es fertig abgearbeitet wurde ("Close and comment").

Ggf. können die entstandenen Artefakte (wenn überhaupt) hier auch sicherheitshalber nochmal verlinkt werden.

**Comment by jomehr** [comment]
Pseudocode für Tags ist fertig. Assetteam muss Code noch mit den Screens aufarbeiten.
