### ISSUE TITLE
T02 WebApp Rahmen optimieren

### ISSUE THREAD

**Issue by vschaefer** [th-koeln/wba1-2016-backslash#122]
Ich gehe mal davon aus, dass der Ordner „Final” wirklich euer finaler Stand ist.

- [x] Bitte mal das Hauptmenü checken, das fehlt in der Desktopansicht
- [x] Bitte Schriftfarbe ändern, wenn man über die Menüpunkte hovert
- [ ] Schließen-Button im Menü der mobilen Ansicht dem Mockup anpassen. Bitte hier den Icon-Font von Team 09 verwenden: https://github.com/th-koeln/wba1-2016-backslash/wiki/T09-CSS#symbole

**Comment by nikcani** [comment]
@vschaefer das Hauptmenü ist aber im finalen Produkt ok, oder? Anstelle der Schriftfarbe würde ich beim hover eher einen border-bottom vorschlagen. Und den Schließen-Button können wir im finalen Produkt auch missachten, weil sich ja der Hamburger zum X animiert, oder? (das ändert natürlich nichts daran, dass T02 die Änderungen bei sich durchführen sollte.)

**Comment by vschaefer** [comment]
Border finde ich auch gut. Hauptsache es tut sich was :)
Beim Rest stimme ich auch zu

**Comment by vschaefer** [comment]
In der finalen App passt das Menü. Wo ist das denn im statischen Screen hingekommen? 
🤔

**Comment by Exokay** [comment]
wir haben in der version die version aus dem ordner zusammenfuehren genommen

**Comment by nikcani** [comment]
@Exokay ja, aber ich habe das css angepasst und gefixt auf deren hinweis hin, deswegen passt das bei uns

**Comment by vschaefer** [comment]
Okay. Hier ist mir aber noch eine Kleinigkeit aufgefallen. Undzwar der vertikale Strich zwischen Login und Registrieren ist ein <a>-Element. Das ist nicht soooo schön.
- [ ] Bitte den Strich mit CSS als Border umsetzen

**Comment by nikcani** [comment]
Strich als Border im finalen Produkt nun ebenfalls umgesetzt, daher auf dem Projektboard finale Arbeiten nun unter Abgeschlossen

**Comment by Darkkap** [comment]
Nicht wundern, dass von uns hier noch nichts kam. Wir haben es auf der Agenda, der Blockkurs frisst etwas Zeit.
Ich denke da nikcani es in der Zusammenführung schon übernommen hat, wäre es cool zu wissen steht der Screenshot noch beim 01.12., für unser Arbeitspaket?
