### ISSUE TITLE
T05 Quizende Finetuning

### ISSUE THREAD

**Issue by vschaefer** [th-koeln/wba1-2016-backslash#123]
- [x] Durchschuss vom Fließtext bitte etwas erhöhen

**Comment by kosimas** [comment]
Bitte was? 😄

**Comment by nikcani** [comment]
[http://www.cleverprinting.de/images/Clever_Typoposter1.jpg](http://www.cleverprinting.de/images/Clever_Typoposter1.jpg)

**Comment by nikcani** [comment]
@kosimas und dann bitte mir die Änderungen mitteilen, damit ich sie auch im finalen Produkt einbauen kann

**Comment by nikcani** [comment]
im finalen Produkt nun umgesetzt, daher auf dem Projektboard finale Arbeiten nun unter Abgeschlossen

@kosimas ich bin jetzt bei ner line-height von 1.3 gelandet

**Comment by kosimas** [comment]
Keine Ahnung wo du das line-height drauf getan hast. Bei mir macht 1.3px alles Kaput, egal wo ich es drauf setze. Habe es jetzt auf 17px gesetzt damit sieht es gut aus.

Und bei jedem Slider-Element müssen die klassen **animated fadeInShort** hinzugefügt werden

```html
<div class="ss_slider_content row animated fadeInShort">
```

**Comment by nikcani** [comment]
hab die sachen eingefügt im finalen und pushe das gleich
