### ISSUE TITLE
T15 Onepager Kapitelsprung

### ISSUE THREAD

**Issue by JPruess** [th-koeln/wba1-2016-backslash#124]
Hallo Volker,
wie besprochen ein Ticket bezüglich Hilfe von Dir wegen des zu weiten Kapitelsprungs der nur bei dem ersten Klick auf einen beliebigen Navigationspunkt passiert.
Wie gesagt habe ich die Vermutung, dass es nur beim ersten Mal passiert, dass zu weit gesprungen wird, da zuerst zu der jeweiligen Headline gesprungen wird und DANACH erst die slicknavi lädt und sich dem entsprechend über den Text legt.

Sonst haben wir nur noch das Problem mit der H1 im Header die sich hinter den Button legt bei der Handyansicht. Eine nicht so elegante Lösung wäre die Schrift ab einer bestimmten Größe auf kleineren pt zu setzen. Aber das ist dann ja auch nur 'gemogelt'. :(
Inzwischen haben insgesamt 5 Leute drüber geguckt und den 'Fehler' nicht finden können.

**Comment by Exokay** [comment]
ist das problem noch offen? sonst bitte closen.

**Comment by vschaefer** [comment]
Da muss ich mich noch drum kümmern.

**Comment by vschaefer** [comment]
@JPruess Sorry ich bekomme das so einfach doch nicht gefixt. Ich müsste dazu das Markup umbauen und das möchte ich nur ungerne. Eine Variante, um das Problem in den Griff zu bekommen ist, dass ihr das Menü immer oben fixiert. Dazu wäre mein Vorschlag, dass man es noch halbtransparent macht und die die Höhe etwas verringernt. Dazu müsste das Log noch etwas kleiner.

**Comment by vschaefer** [comment]
@JPruess Hab's gelöst bekommen.
