### ISSUE TITLE
T12 Tagesplan 20.10.16 Brainstorming / Dokumentation anfertigen

### ISSUE THREAD

**Issue by ChrisHuntscha** [th-koeln/wba1-2016-backslash#24]
Screens analysieren in Bezug auf:
...welche Elemente müssen/können animiert werden.
...welche Screens brauchen Übergänge.
...wie weit geht unser Aufgabenbereich.

**Comment by jhfpereira** [comment]
Das Issue bitte schließen, sofern es fertig abgearbeitet wurde ("Close and comment").

Ggf. können die entstandenen Artefakte (wenn überhaupt) hier auch sicherheitshalber nochmal verlinkt werden.
