### ISSUE TITLE
ToDos an alle Teams bis 26.10.2016

### ISSUE THREAD

**Issue by vschaefer** [th-koeln/wba1-2016-backslash#46]
Hallo zusammen,

damit wir einen Überblick über den aktuellen Stand bekommen und es ein bisschen voran geht, bitten wir alle Teams bis einschließlich dem 26.10.2016 folgende ToDos zu erledigen:
- den aktuellen Stand vom Sourcecode bzw. Artefakten in das Repository von unserer Company pushen. Achtet bittet drauf, dass ihr die Dateien in den Ordner mit eurem Teamkürzel legt. 
- die ToDos für diese Woche eintragen 
- Problemfeld und Zielsetzung dokumentieren 
- Logbuch schreiben. Also dokumentieren, was ihr bisher gemacht habt, auf welche Probleme ihr gestoßen seid und wie ihr sie gelöst habt.
- Bei technischen Problemen bitte an das Supportteam (T1) wenden
- Bei inhaltlichen Fragen bitte an das Doku- und Quliteam (T14) wenden
- @ Doku- und Quliteam, bitte die Qualität der Dokus und Einhaltung der ToDos etwas im Auge behalten 
- @ Supportteam, bitte darauf achten, dass alles an der richten Stelle landet.

Danke und bis Donnerstag :-)

**Comment by l1fecoach** [comment]
on condiction closed();
