### ISSUE TITLE
Erste Templates bauen

### ISSUE THREAD

**Issue by jomehr** [th-koeln/wba1-2016-backslash#55]
Erste Templates anhand Screen Quizrunde von T4 bauen

**Comment by Exokay88** [comment]
Ist das T04 fertig mit dem Statischen Quiz?

**Comment by vschaefer** [comment]
Könnt ihr das Dummy-Template bitte ins Repo pushen.

Danke
Volker

**Comment by Exokay88** [comment]
Gerade schlecht da ich auf der Arbeit bin.

**Comment by vschaefer** [comment]
Kein Problem, muss nicht sofort sein.

**Comment by Exokay88** [comment]
@vschaefer ist hochgeladen inc. serverside api

**Comment by Exokay88** [comment]
@exokay: Für die JSON-Struktur wäre das Team 13 zuständig. (edited)

**Comment by jomehr** [comment]
ein paar JSONS sind im Ordner von T13

**Comment by Exokay88** [comment]
Bitte gebt mit einen Status wie euer stand ist.

**Comment by jomehr** [comment]
Erstes Template ist fertig
