### ISSUE TITLE
ToDos bis 02.11.2016 - HTML/CSS der statischen Seiten fertigstellen

### ISSUE THREAD

**Issue by vschaefer** [th-koeln/wba1-2016-backslash#57]
Hallo,

wir müssen jetzt leider ein bisschen Gas geben, sonst wird es zum Ende hin sehr stressig werden. Besonders für die Teams, deren Arbeit von den statischen Seiten abhängen.
Bitte alle Teams, die die statischen Seiten bauen, bis zum 02.11.2016 
- die CSS-Datei von Team „T09 CSS” einbinden: https://github.com/th-koeln/wba1-2016-backslash/blob/master/T09-CSS/style.css
- und, soweit es geht, das HTML und CSS fertigstellen **und in unser Repository pushen.**

Bitte verwendet das Grid-System, welches in dem Stylesheet eingebunden ist und die Klassen die in dem Stylesheet erstellt wurden.
Informationen zu dem Grid-System und den Klassen findet ihr auf der Wiki-Seite von Team „T09 CSS”: https://github.com/th-koeln/wba1-2016-backslash/wiki/T09-CSS.

Hier ein kleines Video dazu, wie man die Maße von einzelnen Elementen herausfinden kann:
https://youtu.be/3Sx8GoyfuDg.

Der Contentbereich in dem Mockup hat nicht die gleiche Breite, wie es von dem Gridsystem vorgesehen ist.
Das ist nicht schlimm. Bitte haltet euch an die Maße vom Gridsystem und versucht nicht die Vorgaben vom Grid zu umgehen.

Bei Fragen oder Problemen wendet euch an das Supportteam oder das CSS-Team.
Verwendet dazu die Issue-Funktion oder Slack.

**Comment by M-Esra61** [comment]
Hallo,
wir kommen nicht mehr weiter, könnte uns jemand helfen.
**Problem**
-  wir kriegen die Drop-down Elemente nicht hin
-  Der Selectosort lässt sich nicht vergrößern bzw. verschieben
- wir wissen jetzt auch nicht, was für Klassen wir noch erstellen sollen


Wir bedanken uns im Voraus.

Mit freundlichen Grüßen
T06_Startische Quizübersicht

**Comment by jhfpereira** [comment]
Hallo Merve,
habe mir gerade nochmal euren aktuellen Stand angeschaut.

Da gibt es ein paar Dinge, die mir aufgefallen sind und die ihr möglichst als erstes angehen solltet:

1. Euer momentanes HTML-Dokument `Projekt.html` ist nicht valide
2. Ihr setzt verstärkt auf das br-Tag, um Abstände einzuführen
3. Ihr konzentriert euch scheinbar stärker auf die Funktionalität (Sortieren), als auf die sinnvolle und korrekte Auszeichnung mittels HTML und der Formatierung mit CSS

Und nun etwas genauer:

**Zu 1.** Es ist sinnvoll seine HTML-Dokumente in bestimmten Abständen immer wieder zu validieren.
Dazu könnt ihr den offiziellen [Validator des w3c](https://validator.w3.org/#validate_by_input) nutzen. 
Dort einfach den Inhalt eures HTML-Dokuments einfügen und es überprüfen lassen. Die vom Validator identifizierten Problemstellen sollten dann von euch genauer betrachtet und idealerweise behoben werden.

**Zu 2.** Das br-Tag sollte nur innerhalb von Texten genutzt werden, um einen Zeilenumbruch explizit zu erzwingen. Es ist nicht dafür gedacht, um horizontalen Abstand zwischen zwei Elementen einzuführen. Als Alternative bieten sich die CSS-Eigenschaften `margin`- und/oder `padding` an, um den Außen- bzw. Innenabstand eines Elements vorzugeben.

**Zu 3.** Konzentriert euch im ersten Schritt (natürlich nachdem die ersten beiden Punkte abgearbeitet wurden), auf die Struktur des Dokuments und der korrekten Auszeichnung. Erst wenn die Struktur steht, kann man sich im Anschluss, sofern noch Zeit bleibt, um die Funktionalität kümmern.


Weitere Tipps:

1. Es ist sehr gut, dass ihr das Stylesheet von Team 09 eingebunden habt. Damit habt ihrs schon mal Zugriff auf alle grundlegenden Formatierung hinsichtlich Schrift und Farbe. Ihr nutzt ja schon bereits eine durch dieses Stylesheet vorgegebene Regel (`bg-yellow`), um die Hintergrundfarbe des Blockheaders zu setzen.

2. Neben den vorgegebenen CSS-Regeln, wird über das Stylesheet auch ein Grid-System importiert ( Bootstrap Grid-System ). Dadurch habt ihr nun die Möglichkeit, die Quizübersicht komplett mit Hilfe eines Grids aufzusetzen.
Auf der Wiki-Seite von T09 ist ein Link zu einer guten Seite zu finden, wo eine Einführung in das Grid-System zu finden ist. Dort wird auch erklärt, wie man es sinnvoll einsetzt.

3. Um das select-Element formatieren zu können, muss (je nach Browser) die CSS-Eigenschaft `appearance` bzw. `-webkit-appearance` auf `none` gesetzt werden. Mit der Nutzung des Grid-Systems, sollte auch die Positionierung einfacher fallen.

4. Mit dem Grid-System und dem dahinter liegenden Konzept im Hinterkopf, solltet ihr euch die Mockups nochmal hervorholen und überlegen, wo vllt. ein Grid erkennbar ist. Versucht euch die Frage zu stellen, was in einer `row` und was in einer `column` gekapselt werden kann.
**Kleiner Hinweis:** Beim Desktop-Mockup erkenne ich auf den ersten Blick ein dreispaltiges Layout. Im Smartphone-Mockup ist es hingegen einspaltig. Elemente, die im Desktop-Mockup nebeneinander angeordnet werden, sind im Smartphone-Mockup hingegen untereinander angeordnet. Um so etwas zu realisieren, ist ein Grid-System geradezu für prädestiniert.

5. Achtet darauf, dass euer Markup und eure CSS-Regeln sinnvoll eingerückt sind. So wie sie momentan vorliegen, sind sie nämlich schwerer zu lesen und somit auch schwieriger zu ergänzen.

6. Achtet darauf, dass ihr immer stets valides und semantisches Markup schreibt. In euer `Projekt.html`-Datei fällt nämlich auf, dass ihr für offensichtliche Strukturen nicht die passenden HTML-Elemente nutzt, um sie richtig auszuzeichnen. Als Beispiel sei nur die Auflistung der Quize genannt, hinter der offensichtlich eine Liste steckt. Vllt. eine ungeordnete Liste? ;) 
Sind die Listeneinträge erst einmal sinnvoll ausgezeichnet, können sie dann sehr viel einfacher mit Hilfe von JavaScript sortiert werden (auch unter Berücksichtigung dessen, was über das Select-Element ausgewählt wurde -> `change`-Event). 


Ich hoffe sehr, dass ich dir und deinem Team hiermit ein paar gute Tipps und Hinweise geben konnte.

**Comment by nikcani** [comment]
Kann das hier geschlossen oder umbenannt werden, da es ja auf letzte Woche datiert ist?

**Comment by jhfpereira** [comment]
Close es mal, da die meisten stat. Seiten bereits stehen, trotz kleiner Ausnahmen, um die man sich noch gekümmert hat bzw. noch kümmern wird.
