### ISSUE TITLE
Zielsetzung

### ISSUE THREAD

**Issue by DavidZibler** [th-koeln/wba1-2016-backslash#6]
- Wireframes (Bilder, Icons, Buttons zusammensuchen)
- Kontakt zu anderen Teams aufbauen **
- Programm zur Bildbearbeitung und Umsetzung suchen **
- Aufteilung der Aufgaben innerhalb der Gruppe **

**erledigt

**Comment by jhfpereira** [comment]
Das Issue bitte schließen, sofern es fertig abgearbeitet wurde ("Close and comment").

Ggf. können die entstandenen Artefakte (wenn überhaupt) hier auch sicherheitshalber nochmal verlinkt werden.
