### ISSUE TITLE
ToDos bis 02.11.2016 - Animationen und Übergänge

### ISSUE THREAD

**Issue by vschaefer** [th-koeln/wba1-2016-backslash#60]
Bitte den aktuellen Stand der Animationsprototypen und -templates ins Repo pushen und eure bisherigen Überlegungen im Wiki dokumentieren.

**Comment by jhfpereira** [comment]
Issue bitte closen wenn erledigt. Danke :)

Bezüglich der Doku wäre es noch gut, wenn die Überlegungen und Entscheidungen noch mit einigen Grafiken aufgelockert werden, um sich das Ergebnis besser vorstellen zu können.
Z. B. bei sowas wie
> grüner Flash bei falschen Antworten
wäre es ganz gut zu zeigen, wie der "Flash" aussieht. Vllt. als gif-File?
