### ISSUE TITLE
ToDos bis 02.11.2016 - Content bereitstellen

### ISSUE THREAD

**Issue by vschaefer** [th-koeln/wba1-2016-backslash#61]
Bitte euren gesammelten und selbst erstellten Content ins Repo pushen oder auf eurerer Wikiseite bereitstellen.

**Comment by JPruess** [comment]
Der Content wurde auf der unserer T15 Wikiseite (samt Anmerkungen) bereitgestellt.
Morgen (den 03.01.2016) wollen wir dazu gerne mit Volker Schäfer bezüglich Wortlaut und SEO-Einbindung Rücksprache halten um gegebenenfalls noch schnelle Änderungen vornehmen zu können.
