### ISSUE TITLE
ToDos bis 02.11.2016 - Aktuellen Stand des Onepagers bereitstellen

### ISSUE THREAD

**Issue by vschaefer** [th-koeln/wba1-2016-backslash#62]
Bitte den aktuellen Stand des Onepagers ins Repository pushen.
Idealerweise sollte das HTML fertiggestellt sein und das grobe Layout stehen.

**Comment by JPruess** [comment]
Ein aktuelles Layout wurde im T15-Ordner hochgeladen (wie auch noch einmal zusätzlich der Content).

Die aktuelle HTML-Datei folgt von einem weiteren Teammitglied.

**Comment by jhfpereira** [comment]
Schließe das ToDo mal, da Abgabezeitpunkt bereits vergangen.
