### ISSUE TITLE
ToDos bis 03.11.2016 - Meilensteinplan erstellen

### ISSUE THREAD

**Issue by vschaefer** [th-koeln/wba1-2016-backslash#63]
Bitte einen teamübergreifenden Meilensteinplan für die letzten Wochen erstellen.
Die Abschlusspräsentation findet am 24.11.2016 statt, bis dahin muss alles fertig sein.
Das heißt, wir haben jetzt noch 3,5 Wochen Zeit.
Wir brauchen Meilensteine für jede Woche und eine Checkliste, was konkret am Ende fertig sein muss.

**Comment by nikcani** [comment]
Kann das hier geschlossen werden?
