### ISSUE TITLE
ToDo für den 03.11.2016 - HTML reviewen

### ISSUE THREAD

**Issue by vschaefer** [th-koeln/wba1-2016-backslash#64]
Bitte am Donnerstag den HTML-Code der statischen Seiten zusammen mit den einzelnen Teams reviewen. Folgende Punkte sind mir wichtig:
* Das Markup sollte semantisch möglichst reichhaltig sein
* Das Markup muss valide sein
* Die style.css von Team 9 muss eingebunden sein
* Die bereits erstellten CSS-Regeln von Team 9 sollten verwendet werden
* Das Grid-System sollte sinnvoll eingesetzt werden

Bei fragen, könnt ihr gerne hier einen Kommentar hinterlassen oder uns im Slack anhauen.

**Comment by Exokay88** [comment]
edit : 3.11

**Comment by l1fecoach** [comment]
An das liebe Support-Team ich bin gerade dabei mir nach und nach alles anzuschauen. Dabei bräuchte  das Management-Team Unterstützung da wir noch einige andere wichtige Dinge erledigen müssen. Bitte tretet dem Slack bei und schreibt uns an oder wir organisieren eine Skype-Konferenz da ich das Thema bis Sonntag durch haben möchte.
