### ISSUE TITLE
Feedback zu bisher erstellten Artefakten

### ISSUE THREAD

**Issue by vschaefer** [th-koeln/wba1-2016-backslash#65]
Hallo zusammen, 

wir haben uns mal die bisher erstellten Artefakte im Repository und Wiki zu jedem Team angesehen. Uns sind ein paar Dinge aufgefallen die noch bei manchen Teams ausbaufähig sind.
* Die HTML-Dokumente die ihr erstellt, sollten möglichst semantisch reichhaltiges Markup enthalten. Bspw. wenn in dem Dokument eine Auflistung existiert, sollte diese entsprechend als Liste ausgezeichnet sein.
* Zudem müssen die HTML-Dokumente valide sein. Deshalb bitte zwischendurch mal eure HTML-Dokumente durch den Validator jagen: [https://validator.w3.org](https://validator.w3.org)
* Es ist wichtig, dass jedes Team ein möglichst ausführliches Logbuch führt. Es reicht nicht, wenn ihr eure ToDos nur dokumentiert/beschreibt, sondern auch dokumentiert auf welche Probleme ihr beim Abarbeiten des ToDos gestoßen seid und wie ihr diese gelöst habt und was das Endergebnis ist. Das heißt, wenn ihr beispielsweise ein ToDo „Aufteilung der Arbeitspakete” erstellt, solltet ihr auch dokumentieren, wie ihr die Arbeitspakete aufgeteilt habt.  
* Es ist wichtig, dass ihr jede Woche Issues und Wochenziele anlegt. Wenn ihr das Wochenziel nicht erreicht, wäre es optimal, wenn ihr kurz dokumentiert, dass ihr das Wochenziel nicht erreicht habt und warum ihr es nicht erreicht habt.
* Und bitte pusht regelmäßig euren Entwicklungsstand in unser Repository. 

@l1fecoach und @iThink94 , bitte die letzten drei Punkte mit im Auge behalten und bei Optimierungsbedarf ruhig die einzelnen Teams anpieksen.

Ende der Durchsage :-)

**Comment by nikcani** [comment]
Kann das hier geschlossen werden?
