### ISSUE TITLE
Kontakt zum Support Team aufbauen

### ISSUE THREAD

**Issue by DavidZibler** [th-koeln/wba1-2016-backslash#7]
- Fragen klären
     - Zu lizenzfreien Bildern (Webseiten)
     - Welches Team benötigt welche Bilder (Größe etc.)

**Comment by jhfpereira** [comment]
Das Issue bitte schließen, sofern es fertig abgearbeitet wurde ("Close and comment").

Ggf. können die entstandenen Artefakte (wenn überhaupt) hier auch sicherheitshalber nochmal verlinkt werden.
