### ISSUE TITLE
Dokumentation neu aufbereiten

### ISSUE THREAD

**Issue by Darkkap** [th-koeln/wba1-2016-backslash#71]
An T10 orientieren

**Comment by jhfpereira** [comment]
Issue bitte closen wenn erledigt. Danke :)

Unter `Lösungsstrategien` und `Projektergebnis` steht für den 03.11. und 10.11. noch **wird noch ergänzt**. Wäre gut, wenn das noch zeitnah wirklich noch ergänzt wird, da man über die Wochen recht schnell vieles vergisst.
Es reicht auch, wenn man sich auf der Gruppen-Seite zu jedem Tag ein paar Stichwörter macht um sich später wieder besser an den Tag erinnern zu können und was ihr an dem Tag alles gemacht habt bzw. auf welche Probleme ihr ggf. gestoßen seid und wie eure Lösungsansätze aussahen.

**Comment by Darkkap** [comment]
erledigt :)
Danke!
