### ISSUE TITLE
getViewbyId-API funktion & Bugfix/Erklärung von getView(anzahl)

### ISSUE THREAD

**Issue by l1fecoach** [th-koeln/wba1-2016-backslash#79]
In **Slack** wurde eine getViewbyId-API funktion angefordert.  Diese ist **essenziell** für andere Teams, um besser mit den anderen Teams zu kommunizieren bitte ich euch dem **Slack** beizutreten. 

**_quote:_**

>7:21 PMjmd von team 13 hier?
>7:22 Falls ja würde ich gerne eine getViewbyId-API funktion anfordern.
>7:26 bzw bekomme ich beim aufruf von     getQuizView(anzahl);
>ein undefined error BS_API.js:96
>Uncaught TypeError: Cannot read property 'quizID' of undefined
>json_request.on  readystatechange @ BS_API.js:96
>Beim Aufruf mit anzahl=0 bekomme ich ein leeres Objekt wieder. Bei jeder anderen Anzahl den Fehler.

Wenn ihr das Problem erfasst und behoben habt möchte ich diesbezüglich eine Rückmeldung des aktuellen Statusbericht haben. Vergisst dann auch nicht dieses Issue zu closen();

PS: _trotzdem noch ein schönes Wochenende euer l1fecoach_

**Comment by micha997** [comment]
* Hab die Funktion getQuizViewByID(quizID); hinzugefügt. 
 Auf unserer [Wiki-Seite](https://github.com/th-koeln/wba1-2016-backslash/wiki/T13-Datenstruktur&Content#api-nutzung) hab ich die Erklärung auch hinzugefügt
* Das Problem mit getQuizView(anzahl); lag daran, dass jemand die JSON geändert hat. Das hab ich auch behoben. (Bei anzahl=0 bekommt man halt 0 Quizze für die Übersicht)
* Wie die Funktionen funktionieren und wie die ausgegebenen jsons aussehen hab ich alles auf unserer [Wiki-Seite](https://github.com/th-koeln/wba1-2016-backslash/wiki/T13-Datenstruktur&Content#api-nutzung) dokumentiert.
