### ISSUE TITLE
Hilfe Responsive Design T04 - Quizrunde

### ISSUE THREAD

**Issue by dbljn** [th-koeln/wba1-2016-backslash#81]
Hallo,

derzeit versuche ich das Responsive Design unseres statischen Screens zu erarbeiten.
Die allgemeine Ansicht ändert sich über sämtliche Endgeräte nicht, sodass der Aufbau auf Desktop, Smartphone sowie Tablet gleich ist. Einzig und allein die einzelnen Objekte ändern sich in der Größe, dadurch bin ich momentan verwirrt, wie ich das Grid-System einbauen und wie dieses überhaupt aussehen soll.

Ich hoffe und bitte auf baldige Hilfe.

Gruß
Dominik

**Comment by vschaefer** [comment]
Konntest du das Problem lösen oder wurde dir schon geholfen?
Wenn nicht, können wir morgen früh mal zusammen drauf schauen.

**Comment by dbljn** [comment]
Wurde in Slack besprochen.
