### ISSUE TITLE
Html statische Seiten

### ISSUE THREAD

**Issue by AaronWr** [th-koeln/wba1-2016-backslash#82]
Leute, bitte immer den aktuellen Stand pushen, damit wir sehen koennen was fuer Fortschritte gemacht werden.
Wenn ihr Hilfe braucht koennt Ihr mir in Slack direkt schreiben (heisse dort Aaron).
Oder koennt mir auch an meine Mail "aaron.wreschino@smail.th-koeln.de" schreiben.
Statische Seiten sollten bestenfalls Sonntag fertig sein.
LG. Aaron @support.

**Comment by Exokay88** [comment]
gibts es ein update? wie ist der stand?
