### ISSUE TITLE
T07 - richtigen Screen erstellen

### ISSUE THREAD

**Issue by lucastein** [th-koeln/wba1-2016-backslash#83]
- Code von T05-StatSchlussscreen übernehmen und an den T07-StatStartscreen anpassen
- Bei Fragen ins Slack schreiben
- Deadline: Sonntag, den 06.11.2016

**Comment by l1fecoach** [comment]
Wie sieht der Zwischenstand aus? Sind noch knapp 5 Std bitte mal pushen.
