### ISSUE TITLE
T05 - Letzte Fehler fixen 

### ISSUE THREAD

**Issue by iThink94** [th-koeln/wba1-2016-backslash#84]
Bitte die letzten Fehler fixen, damit T08 mit dem Mergen beginnen kann.
* [x] Bilder sind bei Sprung in Tablet Variante zu groß. Bitte mit zwei Spalten umsetzen (Text neben Bild)
* [x] Im mobilen Design bei 320p Breite rutscht der letzte Punkt in die nächste Zeile und hängt direkt unter dem Erstern. Da muss auf jeden Fall noch eine schönere Lösung gefunden werden. Eventuell auch in Absprache mit dem CSS Team.
* [x] Kleinigkeit: Es werden nur drei Random Quiz erwartet

**Comment by jomehr** [comment]
Benutzt bitte den Code mit den Templates aus unserem Ordner (T08) wenn ihr irgendwas fixed, damit wir unseren nicht ständig updaten müssen.

**Comment by Exokay88** [comment]
ob da jetzt 3 oder 4 slider sind macht jetzt keinen unterschied.

**Comment by jhfpereira** [comment]
Kann das Issue somit geclosed werden?
