### ISSUE TITLE
Breakpoints Mockup / Bootstrap

### ISSUE THREAD

**Issue by vschaefer** [th-koeln/wba1-2016-backslash#85]
Ich schlage vor, dass wir das Bootstrap so customizen, dass wir die Breite des Containers von Bootstrap der Breite der Contentbox des Mockups anpassen. Dann können wir das Gridsystem verwenden um die Contentbox zu zentrieren und auch die Breite zu setzen und müssen keine zusätzlichen CSS-Klassen dafür erstellen.

Ich hoffe das war einigermaßen verständlich was ich gemeint habe.

**Comment by nikcani** [comment]
Finde die Idee gut und werde es heute testen und falls vernünftig umsetzbar, wovon ich ausgehe, auch direkt in den Basic Styles übernehmen

**Comment by vschaefer** [comment]
Super, danke.
Ich habe mal nachgesehen, das kann man direkt im Customizer von Boostrap definieren.
http://getbootstrap.com/customize/

**Comment by nikcani** [comment]
So genau hatte ich mir den noch nicht angesehen, guter Tipp. Habe das jetzt darüber umgesetzt und auch noch das Padding rausgenommen für die einfachere Nutzung.
