### ISSUE TITLE
T07 Responsive funktioniert noch nicht richtig

### ISSUE THREAD

**Issue by iThink94** [th-koeln/wba1-2016-backslash#88]
Die Tablet und Smartphone Version funktioniert noch nicht richtig.

**Comment by Stefan1805** [comment]
Wir müssen das Grid-System noch einbauen, hatten damit Probleme. Folgt heute.

**Comment by jhfpereira** [comment]
Das Issue bitten closen, wenn das Problem auch vergangenen Donnerstag gelöst wurde. Danke :)

**Comment by nikcani** [comment]
Ich schließe das hier mal, da ich die Änderungen ja bereits übernommen habe.
