### ISSUE TITLE
T04 - Tagesplanung - 10.11.2016

### ISSUE THREAD

**Issue by dbljn** [th-koeln/wba1-2016-backslash#90]
- Der HTML sowie CSS-Code wird finalisiert. 
- Responsive Design wird ebenfalls finalisiert
- Bugs werden soweit möglich gefixt

**Comment by jhfpereira** [comment]
Issue bitte closen wenn die Liste am vergangenen Donnerstag komplett abgearbeitet wurde und somit erledigt ist. Danke :)
