### ISSUE TITLE
T15 Tagesplanung 10.11 

### ISSUE THREAD

**Issue by hmontada** [th-koeln/wba1-2016-backslash#91]
- **Feinheiten bearbeitet**
- [ ] Feinschliff HTML & CSS
- [ ] Finalen Content überarbeiten
- [x] Parallax Effekt implementieren 
- [ ] Verlinkung Social Media
- [x] Suchfunktion
- [x] T16 das Template zur verfügung stellen
- [ ] Vereinsanpassung 2x Bilder von T10 holen
- [ ] Feedback holen von CEO und Noss

**Comment by jhfpereira** [comment]
Issue bitte closen und für die offenen Punkte in die nächste Tagesplanung (Issue) übernehmen. Danke :)
